// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	book "github.com/eminetto/post-turso/book"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, title, author, category
func (_m *UseCase) Create(ctx context.Context, title string, author string, category book.Category) (book.Book, error) {
	ret := _m.Called(ctx, title, author, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, book.Category) (book.Book, error)); ok {
		return rf(ctx, title, author, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, book.Category) book.Book); ok {
		r0 = rf(ctx, title, author, category)
	} else {
		r0 = ret.Get(0).(book.Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, book.Category) error); ok {
		r1 = rf(ctx, title, author, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *UseCase) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *UseCase) Get(ctx context.Context, id int64) (book.Book, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (book.Book, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) book.Book); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(book.Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *UseCase) List(ctx context.Context) ([]book.Book, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []book.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]book.Book, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []book.Book); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, title, author, category
func (_m *UseCase) Update(ctx context.Context, id int64, title string, author string, category book.Category) error {
	ret := _m.Called(ctx, id, title, author, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, book.Category) error); ok {
		r0 = rf(ctx, id, title, author, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
